//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_information
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string Absence_type { get; set; }
        public string From_date { get; set; }
        public string To_date { get; set; }
        public string Number_of_dayes { get; set; }
        public string Reason_of_absence { get; set; }
        public string Supperviser_status { get; set; }
        public string Supperviser_comments { get; set; }
        public string HR_status { get; set; }
        public string HR_comments { get; set; }
        public string Leave_status { get; set; }
    
        public virtual Employee_information Employee_information { get; set; }
    }
}
